// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeYGTaD_Ycv9awveKgDFJo-jQSLJ_rUcM',
    appId: '1:274555099680:web:89e3795ad98bda21edba45',
    messagingSenderId: '274555099680',
    projectId: 'events-a1d60',
    authDomain: 'events-a1d60.firebaseapp.com',
    storageBucket: 'events-a1d60.appspot.com',
    measurementId: 'G-KWX8X3XD9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV0vusuZcYvleVihYRC5mD8vd4BMLXDVQ',
    appId: '1:274555099680:android:09a4982f309a93b4edba45',
    messagingSenderId: '274555099680',
    projectId: 'events-a1d60',
    storageBucket: 'events-a1d60.appspot.com',
  );
}
